[package]
name = "datadog"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "^1"
bincode = "^1"
dotenvy = "^0"
libsql = "^0"
ntex = { version = "^2", features = ["tokio"] }
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
geni = "1"
