[package]
name = "datadog"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.88"
bincode = "1.3.3"
dotenvy = "0.15.7"
libsql = "0.5.0"
ntex = { version = "2.0", features = ["tokio"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
