
--
-- LibSQL SQL Schema dump automatic generated by geni
--

CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE schema_migrations (id VARCHAR(255) NOT NULL PRIMARY KEY);
CREATE TABLE migrations (id VARCHAR(255) NOT NULL PRIMARY KEY);
CREATE TABLE users (
ID INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT
);